import AppKit
import Foundation

enum ClipboardSecurityPolicy {
    static let maximumTextBytes = 1 * 1_024 * 1_024
    static let maximumImageBytes = 20 * 1_024 * 1_024
    static let maximumImagePixels = 50_000_000

    private static let sensitiveTypeNames: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func shouldCapture(types: [NSPasteboard.PasteboardType]) -> Bool {
        sensitiveTypeNames.isDisjoint(with: types.map(\.rawValue))
    }

    static func acceptsText(_ text: String) -> Bool {
        text.lengthOfBytes(using: .utf8) <= maximumTextBytes
    }

    static func acceptsEncodedImageData(_ data: Data) -> Bool {
        data.count <= maximumImageBytes
    }

    static func acceptsImage(_ image: NSImage) -> Bool {
        guard let dimensions = image.pixelDimensions else { return false }
        guard dimensions.width > 0, dimensions.height > 0 else { return false }
        return dimensions.width <= maximumImagePixels / dimensions.height
    }
}

extension NSImage {
    var pixelDimensions: (width: Int, height: Int)? {
        let representations = representations.filter {
            $0.pixelsWide > 0 && $0.pixelsHigh > 0
        }
        if let largest = representations.max(by: {
            safePixelCount(width: $0.pixelsWide, height: $0.pixelsHigh)
                < safePixelCount(width: $1.pixelsWide, height: $1.pixelsHigh)
        }) {
            return (largest.pixelsWide, largest.pixelsHigh)
        }

        var proposedRect = NSRect(origin: .zero, size: size)
        guard let cgImage = cgImage(
            forProposedRect: &proposedRect,
            context: nil,
            hints: nil
        ) else {
            return nil
        }
        return (cgImage.width, cgImage.height)
    }

    private func safePixelCount(width: Int, height: Int) -> UInt64 {
        let width = UInt64(width)
        let height = UInt64(height)
        let (count, overflow) = width.multipliedReportingOverflow(by: height)
        return overflow ? .max : count
    }
}
